/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package garits.franchisee.discountplan;

import garits.DBConnectivity.DBConnection;
import garits.franchisee.DiscountPlan;
import garits.franchisee.FranchiseeHomePage;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shazidtipu
 */
public class FixedDiscount extends javax.swing.JFrame {

    /**
     * Creates new form FranchiseeEditDiscountPlan
     */
    public FixedDiscount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        fixedIDTextField = new javax.swing.JTextField();
        fixedRateTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        discountTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        fixedDiscountTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        viewCustomersButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        homeButton = new javax.swing.JButton();
        variableDiscountButton = new javax.swing.JButton();
        flexibleDiscountButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        accountHolderTable = new javax.swing.JTable();
        viewFixedPlansButton = new javax.swing.JButton();
        addDiscountPlanButton = new javax.swing.JButton();
        updateDiscountPlan = new javax.swing.JButton();

        jScrollPane4.setViewportView(jEditorPane1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fixedIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixedIDTextFieldActionPerformed(evt);
            }
        });

        discountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Discount_ID", "customerID"
            }
        ));
        jScrollPane1.setViewportView(discountTable);

        fixedDiscountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fixed_ID", "Discount_ID", "Fixed_Rate"
            }
        ));
        jScrollPane2.setViewportView(fixedDiscountTable);

        jLabel1.setText("Fixed Discount");

        viewCustomersButton.setText("View Customers");
        viewCustomersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomersButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Fixed_ID");

        jLabel5.setText("Fixed Rate");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        label1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("GARITS");

        homeButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        variableDiscountButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        variableDiscountButton.setText("Variable Discount Plans");
        variableDiscountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variableDiscountButtonActionPerformed(evt);
            }
        });

        flexibleDiscountButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        flexibleDiscountButton.setText("Flexible Discount Plans");
        flexibleDiscountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flexibleDiscountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(variableDiscountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(flexibleDiscountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(variableDiscountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flexibleDiscountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        accountHolderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "customerID", "discountPlan", "payLater", "credit"
            }
        ));
        jScrollPane3.setViewportView(accountHolderTable);

        viewFixedPlansButton.setText("View Fixed Plans");
        viewFixedPlansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFixedPlansButtonActionPerformed(evt);
            }
        });

        addDiscountPlanButton.setText("Add Discount Plan");
        addDiscountPlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDiscountPlanButtonActionPerformed(evt);
            }
        });

        updateDiscountPlan.setText("Update Discount Plan");
        updateDiscountPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDiscountPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewFixedPlansButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addDiscountPlanButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(updateDiscountPlan, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(57, 57, 57))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel5))
                                                .addGap(58, 58, 58)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(fixedIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                                    .addComponent(fixedRateTextField))))
                                        .addGap(31, 31, 31)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(viewCustomersButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewCustomersButton)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fixedIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fixedRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addComponent(addDiscountPlanButton)
                        .addGap(15, 15, 15)
                        .addComponent(updateDiscountPlan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewFixedPlansButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new FranchiseeHomePage();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void fixedIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixedIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fixedIDTextFieldActionPerformed

    private void variableDiscountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variableDiscountButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new VariableDiscount();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_variableDiscountButtonActionPerformed

    private void flexibleDiscountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flexibleDiscountButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame frame = new FlexibleDiscount();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_flexibleDiscountButtonActionPerformed

    private void viewCustomersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomersButtonActionPerformed
        // TODO add your handling code here:
        try {
            Connection connection = DBConnection.getConnection();
            connection.setAutoCommit(false);
            
            String sqlQuery = "SELECT * FROM AccountHolder";
            String sqlQuery2 = "SELECT * FROM Discount";
            
            PreparedStatement pStatement = connection.prepareStatement(sqlQuery);
            ResultSet resultSet = pStatement.executeQuery();
            
            PreparedStatement pStatement2 = connection.prepareStatement(sqlQuery2);
            ResultSet resultSet2 = pStatement2.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel)accountHolderTable.getModel();
            DefaultTableModel model2 = (DefaultTableModel)discountTable.getModel();
            
            model.setRowCount(0);
            model2.setRowCount(0);
            
            while (resultSet.next()) {
                Object o[] = {
                    resultSet.getString("customerID"), resultSet.getString("discountPlan"), resultSet.getString("payLater"), resultSet.getString("credit")
                };
                model.addRow(o);
               
            }
            
            while (resultSet2.next()) {
                Object o[] = {
                    resultSet2.getString("Discount_ID"), resultSet2.getString("customerID")
                };
                model2.addRow(o);
               
            }
            
            connection.commit();
            connection.setAutoCommit(true);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_viewCustomersButtonActionPerformed

    private void viewFixedPlansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFixedPlansButtonActionPerformed
        // TODO add your handling code here:
        try {
            Connection connection = DBConnection.getConnection();
            String sqlQuery = "SELECT * FROM Fixed";
            PreparedStatement pStatement = connection.prepareStatement(sqlQuery);
            ResultSet resultSet = pStatement.executeQuery();
            DefaultTableModel model = (DefaultTableModel) fixedDiscountTable.getModel();
            model.setRowCount(0);
            while (resultSet.next()) {
                Object o[] = {
                    resultSet.getString("Fixed_ID"), resultSet.getString("Discount_ID"), resultSet.getString("Fixed_Rate")
                };
                model.addRow(o);
                
                        
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_viewFixedPlansButtonActionPerformed

    private void addDiscountPlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDiscountPlanButtonActionPerformed
        // TODO add your handling code here:
        String fixedID = fixedIDTextField.getText();
        String fixedRate = fixedRateTextField.getText();
        int row = discountTable.getSelectedRow();
        String discountID = discountTable.getModel().getValueAt(row, 0).toString();
        
        try {
            Connection connection = DBConnection.getConnection();
            String sqlQuery = "INSERT INTO Fixed (Fixed_ID, Discount_ID, Fixed_Rate) VALUES (?, ?, ?)";
            PreparedStatement pStatement = connection.prepareStatement(sqlQuery);
            pStatement.setString(1, fixedID);
            pStatement.setString(2, discountID);
            pStatement.setString(3, fixedRate);
            pStatement.executeUpdate();
            System.out.println("Added");

        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_addDiscountPlanButtonActionPerformed

    private void updateDiscountPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDiscountPlanActionPerformed
        // TODO add your handling code here:
        String fixedRate = fixedRateTextField.getText();
        int row = fixedDiscountTable.getSelectedRow();
        String discountID = fixedDiscountTable.getModel().getValueAt(row, 1).toString();
        
        try {
            Connection connection = DBConnection.getConnection();
            String sqlQuery = "UPDATE Fixed SET Fixed_Rate = ? WHERE Discount_ID =" + discountID;
            PreparedStatement pStatement = connection.prepareStatement(sqlQuery);
            pStatement.setString(1, fixedRate);
            pStatement.executeUpdate();
            System.out.println("Added");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateDiscountPlanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FixedDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FixedDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FixedDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FixedDiscount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FixedDiscount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accountHolderTable;
    private javax.swing.JButton addDiscountPlanButton;
    private javax.swing.JTable discountTable;
    private javax.swing.JTable fixedDiscountTable;
    private javax.swing.JTextField fixedIDTextField;
    private javax.swing.JTextField fixedRateTextField;
    private javax.swing.JButton flexibleDiscountButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.Label label1;
    private javax.swing.JButton updateDiscountPlan;
    private javax.swing.JButton variableDiscountButton;
    private javax.swing.JButton viewCustomersButton;
    private javax.swing.JButton viewFixedPlansButton;
    // End of variables declaration//GEN-END:variables
}
